version: '3.4'

services:
  app:
    build: .
    environment:
      - CONFIG_FILE=${CONFIG_FILE}
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
    networks:
      - app_net
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "28000:27017"
    networks:
      - app_net
    logging:
      driver: none
networks:
  app_net:
    driver: bridge
